### ISSUE TITLE
guest gets "no venue found"

### ISSUE THREAD

**Issue by gunhaxxor** [inclubit/origoshift#77]
```
manually fetched new clientstate: {connectionId: 'd2d37600-a68d-4dec-bbec-8120a29091ea', userId: 'fc70beb1-ef51-4aa0-878c-f71b2830dde0', username: 'bullrig-trädkoja-05', role: 'guest', currentVenueId: undefined, …}
index-A2PBzseF.js:13 Entering route that requires to be in a venue.
index-A2PBzseF.js:13 Trying to loadAndJoinVenue
index-A2PBzseF.js:11 TRPCClientError: No Venue found
    at It.from (index-A2PBzseF.js:7:76243)
    at Object.next (index-A2PBzseF.js:7:78231)
    at L (index-A2PBzseF.js:7:81112)
    at WebSocket.<anonymous> (index-A2PBzseF.js:7:81330)
Re @ index-A2PBzseF.js:11
(anonymous) @ index-A2PBzseF.js:11
Promise.catch (async)
ne @ index-A2PBzseF.js:11
S @ index-A2PBzseF.js:11
y @ VenueListView-iNYC47F-.js:1
p.value.length.c.onVenuePicked.a.<computed>.a.<computed> @ VenueListView-iNYC47F-.js:1
Kr @ index-A2PBzseF.js:1
Nt @ index-A2PBzseF.js:1
e_ @ index-A2PBzseF.js:1
onClick @ VenueList.vue_vue_type_script_setup_true_lang-IenIt7mw.js:1
Kr @ index-A2PBzseF.js:1
Nt @ index-A2PBzseF.js:1
r @ index-A2PBzseF.js:1
index-A2PBzseF.js:7 Uncaught (in promise) TRPCClientError: No Venue found
    at It.from (index-A2PBzseF.js:7:76243)
    at Object.next (index-A2PBzseF.js:7:78231)
    at L (index-A2PBzseF.js:7:81112)
    at WebSocket.<anonymous> (index-A2PBzseF.js:7:81330)
from @ index-A2PBzseF.js:7
next @ index-A2PBzseF.js:7
L @ index-A2PBzseF.js:7
(anonymous) @ index-A2PBzseF.js:7
Promise.then (async)
ne @ index-A2PBzseF.js:11
S @ index-A2PBzseF.js:11
y @ VenueListView-iNYC47F-.js:1
p.value.length.c.onVenuePicked.a.<computed>.a.<computed> @ VenueListView-iNYC47F-.js:1
Kr @ index-A2PBzseF.js:1
Nt @ index-A2PBzseF.js:1
e_ @ index-A2PBzseF.js:1
onClick @ VenueList.vue_vue_type_script_setup_true_lang-IenIt7mw.js:1
Kr @ index-A2PBzseF.js:1
Nt @ index-A2PBzseF.js:1
r @ index-A2PBzseF.js:1
```

**Comment by gunhaxxor** [comment]
There is some indication this might be related to "old" users treated as logged in. Although that doesn't explain the "No Venue found" error.
